#$Id$

__END__
=encoding euc-jp

=head1 NAME

antispamwiki.inc.pl - PyukiWiki プラグイン

=head1 概要

wikiスパミング防止プラグイン

=head1 重要度

★★☆☆☆

=head1 説明

cookieを用いて、簡易的にwikiスパミングを防止します。

=head1 使用方法

antispamwiki.inc.cgi にリネームして下さい。

=head1 上書きする関数

なし

=head1 参考

=over 4

=item PyukiWiki/Plugin/ExPlugin/gzip

L<@@BASEURL@@/PyukiWiki/Plugin/ExPlugin/gzip/>


=item PyukiWiki CVSレボジトリ

L<@@CVSURL@@/PyukiWiki-Devel/lib/gzip.inc.pl>

=back

=head1 著者

=over 4

@@AUTHOR_NANAMI@@

@@AUTHOR_PYUKI@@

=back

=head1 ライセンス

@@LICENCE_NANAMI@@

=cut
