#$Id$

__END__
=encoding euc-jp

=head1 NAME

linktrack.inc.pl - PyukiWiki プラグイン

=head1 重要度

★☆☆☆☆

=head1 概要

外部リンクへのカウンターを取る

=head1 使用方法

linktrack.inc.cgi にリネームして下さい。

必要な場合、info/setup.cgi に以下の変数を記載して下さい。

$linktrack::ignoredomain = wikiのURL (http://等のプリフィックスは除く）

複数指定する場合は、「,」で区切って指定できます。

例：abcdefg.com/~user,example.com

=head1 参考

右クリックをした時点でも、リンクトラッキングをできるようにしてあります。その時、Status 204 でのHTTPアクセスが発生します。

=head1 上書きする関数

make_link_target

=head1 参考

=over 4

=item PyukiWiki/Plugin/ExPlugin/linktrack

L<@@BASEURL@@/PyukiWiki/Plugin/ExPlugin/linktrack/>

=item PyukiWiki CVSレボジトリ

L<@@CVSURL@@/PyukiWiki-Devel/lib/linktrack.inc.pl>

=back

=head1 著者

=over 4

@@AUTHOR_NANAMI@@

@@AUTHOR_PYUKI@@

=back

=head1 ライセンス

@@LICENSE_NANAMI@@

=cut
