#$Id$

__END__
=encoding euc-jp

=head1 NAME

logs.inc.pl - PyukiWiki プラグイン

=head1 重要度

★★☆☆☆

=head1 概要

アクセスログをプラグイン

=head1 説明

wikiへのアクセスログを取得します。

=head1 使用方法

logs.inc.cgi にリネームして下さい。

logs ディレクトリを作成して下さい。（デフォルト）

=head1 設定

=over 4

=item $logs::compress

重いサイトを運用する時には、0 を設定して下さい。アクセスログが圧縮されません。

また、アクセスログのキャッシュ保持も圧縮されなくなります。

=item $logs::directory

アクセスログの保存先を設定します。

=back

=head1 バグ

この機能を利用すると、以下の初期化が2回行なわれますが、仕様です。

 init_logs が2回呼び出される
 リソースの読み込み（上書きします）
 データベースをクローズし、ディレクトリを再設定し、データベースをオープン

=head1 上書きする関数

ありません

=head1 参考

=over 4

=item PyukiWiki/Plugin/ExPlugin/logs

L<@@BASEURL@@/PyukiWiki/Plugin/ExPlugin/logs/>

=item PyukiWiki CVSレボジトリ

L<@@CVSURL@@/PyukiWiki-Devel/lib/logs.inc.pl>

L<@@CVSURL@@/PyukiWiki-Devel/lib/Nana/Logs.pm>

L<@@CVSURL@@/PyukiWiki-Devel/plugin/logs_viewer.inc.pl>

=back

=head1 著者

=over 4

@@AUTHOR_NANAMI@@

@@AUTHOR_PYUKI@@

=back

=head1 ライセンス

@@LICENSE_NANAMI@@

=cut
