#$Id$

__END__
=encoding euc-jp

=head1 NAME

ogp.inc.pl - PyukiWiki プラグイン

=head1 重要度

★★★★☆

=head1 概要

The Open Graph protocol

=head1 説明

The Open Graph protocol

=head1 使用方法

ogp.inc.cgi にリネームして下さい。

=head1 上書きする関数

ありません

=head1 参考

=over 4

=item PyukiWiki/Plugin/ExPlugin/ogp

L<@@BASEURL@@/PyukiWiki/Plugin/ExPlugin/ogp/>

=item The Open Graph protocol

L<http://ogp.me/>

=item PyukiWiki CVSレボジトリ

L<@@CVSURL@@/PyukiWiki-Devel/lib/ogp.inc.pl>

=back

=head1 著者

=over 4

@@AUTHOR_NANAMI@@

@@AUTHOR_PYUKI@@

=back

=head1 ライセンス

@@LICENSE_NANAMI@@

=cut
