#$Id$

__END__
=encoding euc-jp

=head1 NAME

stdin.inc.pl - PyukiWiki プラグイン

=head1 重要度

★☆☆☆☆

=head1 概要

スクリプトからページへ書き込む

=head1 使用方法

stdin.inc.cgi にリネームして下さい。

echo "mypage=title&mymsg=wikipage" | perl index.cgi cmd=write

=head1 参考

現バージョンでは権限なく書き込むことができます。

プラグインのstdin.inc.plとは別のものです。

=head1 上書きする関数

なし

=head1 参考

=over 4

=item PyukiWiki/Plugin/ExPlugin/stdin

L<@@BASEURL@@/PyukiWiki/Plugin/ExPlugin/stdin/>

=item PyukiWiki CVSレボジトリ

L<@@CVSURL@@/PyukiWiki-Devel/lib/stdin.inc.pl>

=back

=head1 著者

=over 4

@@AUTHOR_NANAMI@@

@@AUTHOR_PYUKI@@

=back

=head1 ライセンス

@@LICENSE_NANAMI@@

=cut
