#$Id$

__END__
=encoding euc-jp

=head1 NAME

adminchangepassword.inc.pl - PyukiWiki 管理者向けプラグイン

=head1 概要

 ?cmd=adminchangepassword

=head1 重要度

★★★★★

=head1 説明

管理パスワード（凍結・添付）を変更する。

=head1 参考

=over 4

=over 4

=item PyukiWiki/Plugin/Admin/adminchangepassword

L<@@BASEURL@@/PyukiWiki/Plugin/Admin/adminchangepassword/>

=item PyukiWiki CVS

L<@@CVSURL@@/PyukiWiki-Devel/plugin/adminchangepassword.inc.pl>

=back

=head1 著者

=over 4

@@AUTHOR_NANAMI@@

@@AUTHOR_PYUKI@@

=back

=head1 ライセンス

@@LICENSE_NANAMI@@

=cut
