#$Id$
__END__

=head1 NAME

agent.inc.pl - PyukiWiki プラグイン

=head1 概要

 #agent(ブラウザ名、OS名、またはロボット名の正規表現、 マッチした時のページ、 [、 マッチしなかった時のページ)

=head1 重要度

★★☆☆☆

=head1 説明

ユーザーエイジェントに基づいて、表示するページを指定する。

=head1 注意

各ページで画像をattach等でアップロードする場合、このプラグインを設置するページにアップロードしなければなりません。

=head1 使用方法

 #agent(msie,Internet Explorer Page,Sorry)
 #agent(msie32,Internet Explorer 32bit Page,Sorry) on pure 32bit OS of IE
 #agent(msiex86/9,Internet Explorer 32bit Page,Sorry) is 32bit browser on 64bit OS of IE
 #agent(msiex64/10.0,Internet Explorer 64bit Page,Sorry) on pure 64bit browser of IE
 #agent(firefox/3+,FireFox or later Page,Sorry)
 #agent(win,Windows Page,Sorry)
 #agent(mac,Mac Only!,Sorry)
 #agent(bot,Sorry bot)

=head1 参考

=over 4

=item PyukiWiki/Plugin/Standard/agent

L<@@BASEURL@@/PyukiWiki/Plugin/Standard/agent/>

=item PyukiWiki CVS

L<@@CVSURL@@/PyukiWiki-Devel/plugin/agent.inc.pl>

L<@@CVSURL@@/PyukiWiki-Devel/lib/AWS/browsers.pm>

L<@@CVSURL@@/PyukiWiki-Devel/lib/AWS/domains.pm>

L<@@CVSURL@@/PyukiWiki-Devel/lib/AWS/operating_systems.pm>

L<@@CVSURL@@/PyukiWiki-Devel/lib/AWS/robots.pm>

=back

=head1 著者

=over 4

@@AUTHOR_NANAMI@@

@@AUTHOR_PYUKI@@

=back

=head1 ライセンス

@@LICENSE_NANAMI@@

=cut
