#$Id$

__END__
=encoding euc-jp

=head1 NAME

clear.pl - PyukiWiki / YukiWiki プラグイン

=head1 概要

 &clear;

=head1 重要度

★★☆☆☆

=head1 説明

指定した位置に、CSSのクラスの'clear' (clear:both) を挿入します。

テキストの回りこみが解除できます。

=head1 参考

=over 4

=item PyukiWiki/Plugin/Standard/clear

L<@@BASEURL@@/PyukiWiki/Plugin/Standard/clear/>

=item PyukiWiki CVS

L<@@CVSURL@@/PyukiWiki-Devel/plugin/clear.pl>

=back

=head1 著者

=over 4

@@AUTHOR_NANAMI@@

@@AUTHOR_PYUKI@@

=back

=head1 ライセンス

@@LICENSE_NANAMI@@

=cut
