#$Id$

__END__
=encoding euc-jp

=head1 NAME

compressbackup.inc.pl - PyukiWiki 管理者向けプラグイン

=head1 概要

 ?cmd=compressbackup

=head1 説明

バックアップディレクトリを再圧縮します。

=head1 参考

=over 4

=item PyukiWiki/Plugin/Admin/compressbackup

L<@@BASEURL@@/PyukiWiki/Plugin/Admin/compressbackup/>

=item PyukiWiki CVS

L<@@CVSURL@@/PyukiWiki-Devel/plugin/compressbackup.inc.pl>

=back

=head1 著者

=over 4

@@AUTHOR_NANAMI@@

@@AUTHOR_PYUKI@@

=back

=head1 ライセンス

@@LICENSE_NANAMI@@

=cut
