#$Id$

__END__
=encoding euc-jp

=head1 NAME

contents.inc.pl - PyukiWiki プラグイン

=head1 概要

 # contents
 # contents(他のページ名)

=head1 重要度

★★★☆☆

=head1 説明

設置したページ中の見出しの一覧を表示します。

=head1 参考

=over 4

=item PyukiWiki/Plugin/Standard/contents

L<@@BASEURL@@/PyukiWiki/Plugin/Standard/contents/>

=item PyukiWiki CVS

L<@@CVSURL@@/PyukiWiki-Devel/plugin/contents.inc.pl>

=back

=head1 著者

=over 4

@@AUTHOR_NEKYO@@

@@AUTHOR_PYUKI@@

=back

=head1 ライセンス

@@LICENSE_NEKYO@@

=cut
