#$Id$

__END__
=encoding euc-jp

=head1 NAME

links.inc.pl - PyukiWiki プラグイン

=head1 概要

 #links

=head1 重要度

★★☆☆☆

=head1 説明

自動的に逆リンクを行なうプラグイン

=head1 参考

=over 4

=item PyukiWiki/Plugin/Standard/links

L<@@BASEURL@@/PyukiWiki/Plugin/Standard/links/>

=item PyukiWiki CVS

L<@@CVSURL@@/PyukiWiki-Devel/plugin/links.inc.pl>

=item YukiWiki

=back

=head1 著者

=over 4

@@AUTHOR_NEKYO@@

@@AUTHOR_PYUKI@@

=back

=head1 ライセンス

@@LICENSE_NEKYO@@

=cut
