#$Id$

__END__
=encoding euc-jp

=head1 NAME

multiarticle.inc.pl - PyukiWiki プラグイン

=head1 概要

 #multiarticle(name=name,subject=subject,textarea=comment,commentname=name,commenttextarea=comment)

 #multiarticle(name=お名前,url=Webページ=http://,mail=メールアドレス=,
 select=選択ラベル=選択肢１|選択肢２|選択肢３|選択肢４|選択肢５,
 checkbox=チェックボックス=checked,checkbox=チェックボックス,
 star=点数,subject=タイトル,textarea=テキスト,
 commentlabel=コメントする,commentname=お名前,commenturl=Webページ=http://,
 commentmail=メールアドレス（任意）=,commenttextarea=コメント)

=head1 重要度

★☆☆☆☆

=head1 説明

高機能BBS風プラグイン

=head1 設定

=head2 pyukiwiki.ini.cgiの設定

=over 4

=item $::writefrozenplugin

１の場合、凍結されたページでも書き込めるようにする。

=back

=head2 multiarticle.inc.plの設定

=over 4

=item $multiarticle::cols

テキストエリアのカラム数

=item  $multiarticle::rows

テキストエリアの行数

=item $multiarticle::name_cols

名前テキストエリアのカラム数

=item $multiarticle::subject_cols

題名テキストエリアのカラム数

=item $multiarticle::name_format

名前の挿入フォーマット（リソースに記述されています）

=item $multiarticle::subject_format

題名の挿入フォーマット

=item $multiarticle::ins

挿入する位置 1:欄の前 0:欄の後

=item $multiarticle::comment

書き込み下に一行コメントを 1:入れる 0:入れない

=item $multiarticle::auto_br

改行を自動的に変換する 1:する 0:しない

=item $multiarticle::noname

1 の場合、名前なしで処理しない

=item $multiarticle::nosubject

1 の場合、題名なしで処理しない

=back

=head1 参考

=over 4

=item PyukiWiki/Plugin/Standard/multiarticle

L<@@BASEURL@@/PyukiWiki/Plugin/Standard/multiarticle/>

=item PyukiWiki CVS

L<@@CVSURL@@/PyukiWiki-Devel/plugin/multiarticle.inc.pl>

=back

=head1 著者

=over 4

@@AUTHOR_NANAMI@@

@@AUTHOR_PYUKI@@

=back

=head1 ライセンス

@@LICENSE_NANAMI@@

=cut
