#$Id$

__END__
=encoding euc-jp

=head1 NAME

new.inc.pl - PyukiWiki プラグイン

=head1 概要

 &new{2006-01-01 (Sun) 00:00:00};

=head1 重要度

★★★☆☆

=head1 説明

指定した日時が最近であった場合、最近更新された事を強調表示します。

標準では5日以内の場合に New を、１日以内の場合に New! を表示します。期間や表示する文字列のパターンは設置者によってカスタマイズ可能です。

=head1 使用方法

 &new{date-format};

=head1 設定

=item my $new_dates_short

New!を表示する時間を秒で指定します。

=item my $new_dates_long

Newを表示する時間を秒で指定します。

=item my $new_string_short

$new_dates_shortで指定された時間に表示される文字列をHTMLで設定します。

=item my $new_string_long

$new_dates_longで指定された時間に表示される文字列をHTMLで設定します。

=back

=head1 参考

=over 4

=item PyukiWiki/Plugin/Standard/new

L<@@BASEURL@@/PyukiWiki/Plugin/Standard/new/>

=item PyukiWiki CVS

L<@@CVSURL@@/PyukiWiki-Devel/plugin/new.inc.pl>

=back

=head1 著者

=over 4

@@AUTHOR_NEKYO@@

@@AUTHOR_PYUKI@@

=back

=head1 ライセンス

@@LICENSE_NEKYO@@

=cut
