#$Id$

__END__
=encoding euc-jp

=head1 NAME

online.inc.pl - PyukiWiki プラグイン

=head1 概要

 &online;
 #online

=head1 重要度

★★☆☆☆

=head1 説明

現在参照している、おおよそのユーザー数を表示します。

=head1 参考

=over 4

=item PyukiWiki/Plugin/Standard/online

L<@@BASEURL@@/PyukiWiki/Plugin/Standard/online/>

=item PyukiWiki CVS

L<@@CVSURL@@/PyukiWiki-Devel/plugin/online.inc.pl>

=back

=head1 著者

=over 4

@@AUTHOR_NEKYO@@

@@AUTHOR_PYUKI@@

=back

=head1 ライセンス

@@LICENSE_NEKYO@@

=cut
