#$Id$

__END__
=encoding euc-jp

=head1 NAME

setting.inc.pl - PyukiWiki プラグイン

=head1 概要

 ?cmd=setting
 lib/setting.inc.pl を lib/setting.inc.cgi にリネーム

=head1 重要度

★★★★☆

=head1 説明

ユーザーの閲覧環境の設定をして、cookieに保存します。

=head1 設定

=head2 pyukiwiki.ini.cgi

=over 4

=item $::use_Setting

メニューの設定リンクを有効にします。

=item $::cookie_expire

保存cookieの有効期限を設定します。

=item $::cookie_refresh

保存cookieのリフレッシュ間隔を設定します。

=item $::write_location=1

Location移動が有効になってないと使用できません。

=back

=head2 resource/setting.(lang).txt

=over 4

=item plugin_setting_(itemname)

設定項目名を指定します。

=item plugin_setting_(itemname)_check

この設定をできるか否かを指定します。最初に sub という文字列がある場合、それ以降の perl スクリプトを実行します。

1で設定画面は有効、0 で設定画面は無効にします。

この設定をしない場合は、有効とみなします。

=item plugin_setting_(itemname)_list

設定項目のリストを設定します。

設定値:設定名,設定値:設定名 のように指定します。

また、最初に sub という文字列がある場合、それ以降の perl スクリプトを実行し、その返値の配列をリストと指定します。

=item plugin_setting_(itemname)_default

設定項目のデフォルト値を設定します。

また、最初に sub という文字列がある場合、それ以降の perl スクリプトを実行し、その返値をデフォルト値と指定します。

=back

=head1 参考

=over 4

=item PyukiWiki/Plugin/Admin/setting

L<@@BASEURL@@/PyukiWiki/Plugin/Admin/setting/>

=item PyukiWiki CVS

L<@@CVSURL@@/PyukiWiki-Devel/plugin/setting.inc.pl>

L<@@CVSURL@@/PyukiWiki-Devel/lib/setting.inc.pl>

=back

=head1 著者

=over 4

@@AUTHOR_NANAMI@@

@@AUTHOR_PYUKI@@

=back

=head1 ライセンス

@@LICENSE_NANAMI@@

=cut
