#$Id$

__END__
=encoding euc-jp

=head1 NAME

showrss.inc.pl - PyukiWiki プラグイン

=head1 重要度

★☆☆☆☆

=head1 概要

 #showrss(rdfへのURI,[recent|body|menubar],時間,時間フォーマットフラグ,詳細フラグ）

=head1 説明

rdfを読込んで表示します。

時間は1時間単位でキャッシュの有効時間を指定します。0を指定するとキャッシュを使用しません。

指定しない場合は、デフォルトの1時間となります。

cache ディレクトリを作成する必要があります。

=head1 USING

=over 4

=item [recent|body|menubar]

表示する書式を 'recent', 'body' or 'menubar' または未指定から選択します。

=item 時間

更新周期を指定します。

=item 時間フォーマットフラグ

2を設定することで日付を、3を設定することで日時を表示します。

=item 詳細フラグ

1を設定することで、descriptionタグを表示します。（ただし複数行未対応）

=back

=head1 参考

=over 4

=item PyukiWiki/Plugin/Standard/showrss

L<@@BASEURL@@/PyukiWiki/Plugin/Standard/showrss/>

=item PyukiWiki CVS

L<@@CVSURL@@/PyukiWiki-Devel/plugin/showrss.inc.pl>

=back

=head1 著者

=over 4

@@AUTHOR_NEKYO@@

@@AUTHOR_PYUKI@@

=back

=head1 ライセンス

@@LICENSE_NEKYO@@

=cut
