#$Id$
=head1 NAME

smedia.inc.pl - PyukiWiki プラグイン

=head1 概要

 #smedia([menubar|sidebar],[options=value[,options=value]])

 &smedia([menubar|sidebar],[options=value[,options=value]]);

=head1 説明

ソーシャルメディアのリンクを生成する。

=head1 重要度

★★☆☆☆

=head1 注意

XHTML1.1モードでは動作しません。

同じページに２つ以上設置することはできません。

=head1 簡単なサービス登録方法

=over 4

=item Twitter

以下のURLから登録する。

L<https://twitter.com/about/resources/buttons#tweet>

=item FaceBook

以下のURLから登録する。

L<http://developers.facebook.com/docs/reference/plugins/like/>

=item google+

以下のURLから登録する。

L<http://www.google.com/intl/ja/webmasters/+1/button/index.html>

=item はてなブックマーク（日本語のみ）

以下のURLから登録する。

L<http://b.hatena.ne.jp/guide/bbutton>

=item mixiチェック

以下のURLからDeveloper登録を行なう。要携帯メールアドレス

L<https://mixi.jp/guide_developer.pl>

mixi Developper Center L<http://developer.mixi.co.jp/> の mixi Developer Dashboard L<https://sap.mixi.jp/home.pl> から チェックキーの発行を行なう。

トップページから、mixi Plugin にアクセスする。

左メニューから、「新規サービス追加」をクリックする。

必要な情報を記述すると、チェックキーが発行されるので、$smedia::mixi{"data-key"}=""; の中にチェックキーを代入する。

=back

=head1 参考

=over 4

=item PyukiWiki/Plugin/Standard/smedia

L<@@BASEURL@@/PyukiWiki/Plugin/Standard/smedia/>

=item PyukiWiki CVS

L<@@CVSURL@@/PyukiWiki-Devel/plugin/smedia.inc.pl>

=back

=head1 著者

=over 4

@@AUTHOR_NANAMI@@

@@AUTHOR_PYUKI@@

=back

=head1 ライセンス

@@LICENSE_NANAMI@@

=cut
