#$Id$

__END__
=encoding euc-jp

=head1 NAME

stdin.inc.pl - PyukiWiki 管理者向けプラグイン

=head1 概要

 REQUEST_METHOD="GET" QUERY_STRING="cmd=stdin" perl index.cgi < textfile

 setenv REQUEST_METHOD=GET
 setenv QUERY_STRING="cmd=stdin"
 perl index.cgi <textfile > htmlfile


=head1 重要度

☆☆☆☆☆

=head1 説明

UNIXシェル等からの標準入力からwiki文を入力して、簡単にHTMLに整形したものを出力します。

=head1 注意

編集画面のプレビューの相当画面が出力されます。

画像や添付ファイルは認識できません。

完全なHTMLが出力されるわけではありません。

プラグインは、現状、#contents しか対応していません。

=head1 参考

Exプラグインのstdin.inc.plとは別のものです。

=head1 参考

=over 4

=item PyukiWiki/Plugin/Admin/stdin

L<@@BASEURL@@/PyukiWiki/Plugin/Admin/stdin/>

=item PyukiWiki CVS

L<@@CVSURL@@/PyukiWiki-Devel/plugin/stdin.inc.pl>

=back

=head1 著者

=over 4

@@AUTHOR_NANAMI@@

@@AUTHOR_PYUKI@@

=back

=head1 ライセンス

@@LICENSE_NANAMI@@

=cut
