#$Id$

__END__
=encoding euc-jp

=head1 NAME

vote.inc.pl - PyukiWiki プラグイン

=head1 概要

 #vote(選択肢１,選択肢２,選択肢３[投票数],[[WikiName]][投票数]…)
 #vote(選択肢１,選択肢２,選択肢３[投票数],[[WikiName]][投票数]…,add)
 #vote(選択肢１,選択肢２,選択肢３[投票数],[[WikiName]][投票数]…,complete)

=head1 重要度

★★☆☆☆

=head1 説明

選択肢と投票ボタンが並んだフォームを表示する。。

=head1 使い方

=over 4

=item add

訪問者が自由に選択肢を入力できるようにする。

=item complete

投票を終了する。

=back

=head1 備考

凍結していないページであれば、第３者が投票内容を改ざんできる為、厳密な投票には向きません。

ページを凍結して、設置することをお勧めします。

=head1 参考

=over 4

=item PyukiWiki/Plugin/Standard/vote

L<@@BASEURL@@/PyukiWiki/Plugin/Standard/vote/>

=item PyukiWiki CVS

L<@@CVSURL@@/PyukiWiki-Devel/plugin/vote.inc.pl>

=back

=head1 著者

=over 4

@@AUTHOR_NEKYO@@

@@AUTHOR_PYUKI@@

=back

=head1 ライセンス

@@LICENSE_NEKYO@@

=cut
