#$Id$

__END__
=encoding euc-jp

=head1 NAME

yetlist.inc.pl - PyukiWiki プラグイン

=head1 概要

 ?cmd=yetlist

=head1 重要度

★★☆☆☆

=head1 説明

まだ作られていないページを一覧表示します。

まだ作られていないページとは、既存のページでWikiNameあるいはBracketNameで指定されていて、まだ作られていないページです。

=head1 注意

自分以外の誰かがページを書くかもしれないという点は非常にWiki的ですが、実際の運用面ではcommentに記述された一見さんの名前やWikiName同様のパラメータ名など、ページ化しにくいキーワードが大量に引っかかってしまいます。

=head1 参考

=over 4

=item PyukiWiki/Plugin/Standard/yetlist

L<@@BASEURL@@/PyukiWiki/Plugin/Standard/yetlist/>

=item PyukiWiki CVS

L<@@CVSURL@@/PyukiWiki-Devel/plugin/yetlist.inc.pl>

=back

=head1 著者

=over 4

@@AUTHOR_NANAMI@@

@@AUTHOR_PYUKI@@

=back

=head1 ライセンス

@@LICENSE_NANAMI@@

=cut
