#$Id$

__END__
=encoding euc-jp

=head1 NAME

Nana::Search - 日本語あいまい検索モジュール

=head1 概要

 use Nana::Search qw(Search);
 Search(text, search_words);

Internal charactor set is Japanese of EUC or UTF8 only

=head1 サンプル

 "FrontPage" は、以下の検索ワードでヒットします。
  FRoNTpAGe , ＦＲＯＮＴｐａｇｅ(全角文字)
 "うぃき" は以下の検索ワードでヒットします。
 ういき ウイキ ウィキ うゐき etc...
 "あたしネカマなのなの。だから、告白しないでね" は以下の検索ワードでヒットします。
 ナノダカラ あたしねかま ダカラ告白

=head1 著者

=over 4

@@AUTHOR_NANAMI@@

@@AUTHOR_PYUKI@@

=head1 LICENSE

@@LICENSE_NANAMI@@

=cut
